# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_reviewer_app', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='users',
            field=models.ManyToManyField(related_name='user_reviews', to='belt_reviewer_app.User'),
        ),
    ]
