# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_reviewer_app', '0006_auto_20180718_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
